# fly.toml app configuration file generated for floral-morning-2932 on 2023-08-10T12:36:34-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "floral-morning-2932"
primary_region = "gru"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
